//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alphaleonis.Win32 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alphaleonis.Win32.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlphaFS Internal Error:
        ///.
        /// </summary>
        internal static string AlphaFSInternalError {
            get {
                return ResourceManager.GetString("AlphaFSInternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must not be empty.
        /// </summary>
        internal static string ArgumentMustNotBeEmpty {
            get {
                return ResourceManager.GetString("ArgumentMustNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrectly implemented function attempting to generate exception from successful operation.
        ///.
        /// </summary>
        internal static string AttemptingToGenerateExceptionFromSuccessfulOperation {
            get {
                return ResourceManager.GetString("AttemptingToGenerateExceptionFromSuccessfulOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer is not large enough for the requested operation..
        /// </summary>
        internal static string BufferIsNotLargeEnoughForTheRequestedOperation {
            get {
                return ResourceManager.GetString("BufferIsNotLargeEnoughForTheRequestedOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count must not be negative..
        /// </summary>
        internal static string CountMustNotBeNegative {
            get {
                return ResourceManager.GetString("CountMustNotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory not empty.
        /// </summary>
        internal static string DirectoryNotEmpty {
            get {
                return ResourceManager.GetString("DirectoryNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory not found.
        /// </summary>
        internal static string DirectoryNotFound {
            get {
                return ResourceManager.GetString("DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error code was: {0}.
        /// </summary>
        internal static string ErrorCodeWas0 {
            get {
                return ResourceManager.GetString("ErrorCodeWas0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating hard-links on non-NTFS partitions is not supported.
        /// </summary>
        internal static string HardLinksOnNonNTFSPartitionsIsNotSupported {
            get {
                return ResourceManager.GetString("HardLinksOnNonNTFSPartitionsIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal path: {0}.
        /// </summary>
        internal static string IllegalPath0 {
            get {
                return ResourceManager.GetString("IllegalPath0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete header read..
        /// </summary>
        internal static string IncompleteHeaderRead {
            get {
                return ResourceManager.GetString("IncompleteHeaderRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid directory name.
        /// </summary>
        internal static string InvalidDirectoryName {
            get {
                return ResourceManager.GetString("InvalidDirectoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file name: {0}.
        /// </summary>
        internal static string InvalidFileName0 {
            get {
                return ResourceManager.GetString("InvalidFileName0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid handle.
        /// </summary>
        internal static string InvalidHandle {
            get {
                return ResourceManager.GetString("InvalidHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid search pattern.
        /// </summary>
        internal static string InvalidSearchPattern {
            get {
                return ResourceManager.GetString("InvalidSearchPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid security descriptor returned from system..
        /// </summary>
        internal static string InvalidSecurityDescriptorReturnedFromSystem {
            get {
                return ResourceManager.GetString("InvalidSecurityDescriptorReturnedFromSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid transaction object.
        /// </summary>
        internal static string InvalidTransaction {
            get {
                return ResourceManager.GetString("InvalidTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid transaction request.
        /// </summary>
        internal static string InvalidTransactionRequest {
            get {
                return ResourceManager.GetString("InvalidTransactionRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file or directory is not a reparse point.
        /// </summary>
        internal static string NotAReparsePoint {
            get {
                return ResourceManager.GetString("NotAReparsePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset must not be negative..
        /// </summary>
        internal static string OffsetMustNotBeNegative {
            get {
                return ResourceManager.GetString("OffsetMustNotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path already exists.
        /// </summary>
        internal static string PathAlreadyExists {
            get {
                return ResourceManager.GetString("PathAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This stream does not support seeking..
        /// </summary>
        internal static string ThisStreamDoesNotSupportSeeking {
            get {
                return ResourceManager.GetString("ThisStreamDoesNotSupportSeeking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactional conflict.
        /// </summary>
        internal static string TransactionalConflict {
            get {
                return ResourceManager.GetString("TransactionalConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction already aborted.
        /// </summary>
        internal static string TransactionAlreadyAborted {
            get {
                return ResourceManager.GetString("TransactionAlreadyAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction already committed.
        /// </summary>
        internal static string TransactionAlreadyCommitted {
            get {
                return ResourceManager.GetString("TransactionAlreadyCommitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction not active.
        /// </summary>
        internal static string TransactionNotActive {
            get {
                return ResourceManager.GetString("TransactionNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction not requested.
        /// </summary>
        internal static string TransactionNotRequested {
            get {
                return ResourceManager.GetString("TransactionNotRequested", resourceCulture);
            }
        }
    }
}
